VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
    config.vm.provider :libvirt do |libvirt|
        libvirt.host = 'localhost'
        libvirt.username = 'alex'
        libvirt.connect_via_ssh = true
    end
    config.vm.define :libvirt_vm do |machine|
        machine.vm.box = "debian/jessie64"
    end
end
